"use client";

// Programmer Name  : Muhammad Qayyum Bin Mahamad Yazid, Software Engineering Degree Student, APU
// Program Name     : frontend/app/verify/page.tsx
// Description      : Public verify page for anyone to verify a credential on the blockchain.
//                    Accepts ?tokenId=X&holder=0xABC URL params (generated by QR codes on
//                    credential cards) and passes them to VerifyForm for auto-verification.
// First Written on : Saturday, 14-Mar-2026
// Last Modified on : Friday, 10-Apr-2026

import BECPLogo from "@/components/logo/becp-logo";
import VerifyForm from "./verify-form";
import { WagmiProvider } from "wagmi";
import { wagmiConfig } from "@/lib/wagmi/config";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Suspense } from "react";

export default function VerifyPage() {
  const queryClient = new QueryClient();
  return (
    <WagmiProvider config={wagmiConfig}>
      <QueryClientProvider client={queryClient}>
        <div className="relative grid w-screen h-screen place-items-center bg-chart-1">
          <div className="noise-overlay"></div>
          <div className="flex flex-col gap-4 items-center">
            <BECPLogo className="w-48 z-10" />
            <Suspense>
              <VerifyForm />
            </Suspense>
          </div>
        </div>
      </QueryClientProvider>
    </WagmiProvider>
  );
}
